/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClaroRouteImport } from './routes/claro'
import { Route as BellinzonaRouteImport } from './routes/bellinzona'
import { Route as IndexRouteImport } from './routes/index'

const ClaroRoute = ClaroRouteImport.update({
  id: '/claro',
  path: '/claro',
  getParentRoute: () => rootRouteImport,
} as any)
const BellinzonaRoute = BellinzonaRouteImport.update({
  id: '/bellinzona',
  path: '/bellinzona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bellinzona': typeof BellinzonaRoute
  '/claro': typeof ClaroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bellinzona': typeof BellinzonaRoute
  '/claro': typeof ClaroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bellinzona': typeof BellinzonaRoute
  '/claro': typeof ClaroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bellinzona' | '/claro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bellinzona' | '/claro'
  id: '__root__' | '/' | '/bellinzona' | '/claro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BellinzonaRoute: typeof BellinzonaRoute
  ClaroRoute: typeof ClaroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/claro': {
      id: '/claro'
      path: '/claro'
      fullPath: '/claro'
      preLoaderRoute: typeof ClaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bellinzona': {
      id: '/bellinzona'
      path: '/bellinzona'
      fullPath: '/bellinzona'
      preLoaderRoute: typeof BellinzonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BellinzonaRoute: BellinzonaRoute,
  ClaroRoute: ClaroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
